name: CI Checks
 
on:
  push:
    branches:
      - main
jobs:
  test:
    name: Test Application
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v4
      with:
        go-version: '>=1.21.0'
    - run: go version
    - name: Downloads
      run: go get -t ./...
    - name: Run Test
      run: go test ./...
  build:
    name: Build App
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v4
      with:
        go-version: '>=1.21.0'
    - run: go version
 
    - name: Build
      run: make build
 
    - name: Copy Files
      run: |
           mkdir  artifacts
           cp api artifacts/.
 
    - name: Archive
      uses: actions/upload-artifact@v2
      with:
          name: api
          path: artifacts